### ISSUE TITLE
createTopicBrowser Error

### ISSUE THREAD

**Issue by bobvdvelde** [vanatteveldt/topicbrowser#2]
The topicbrowser seems to fail when writting a topic model. 

**Command**:

output <- createTopicBrowser(noun_model, tokens[tokens$pos %in% nouns, "lemma"],tokens[tokens$pos %in% nouns, "aid"], tokens[tokens$pos %in% nouns, "word"], meta=meta )

**Raises:** 
Error in sink(output) : 
'file' must be NULL, a connection or a character string

**Comment by yipcma** [comment]
createTopicBrowser requires a clusterinfo object. I do encounter another error in "info not found"

**Comment by vanatteveldt** [comment]
Thanks for the comment, I'll have a look at the issue this weekend. Can you post the code you're using and the complete error message?

**Comment by yipcma** [comment]
I've filed a separate issue #3

**Comment by vanatteveldt** [comment]
(assuming Bob wasn't waiting anymore after a year? :))
